TecReview/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using TecReview.Models;

namespace TecReview.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly TecReviewContext _context;

        public CategoriesController(TecReviewContext context)
        {
            _context = context;
        }

        // GET: Categories
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["Items"] = await _context.Items
                .Where(x => x.CategoryId == id).ToListAsync();

            if (id == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        // GET: Categories/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("CategoryId, Name, Description, Color")] Category categoryModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoryModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoryModel);
        }

        // GET: Categories/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories.FindAsync(id);
            if (categoryModel == null)
            {
                return NotFound();
            }
            return View(categoryModel);
        }

        // POST: Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId, Name, Description, Color")] Category categoryModel)
        {
            if (id != categoryModel.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryModelExists(categoryModel.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryModel);
        }

        // GET: Categories/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Remove items of the selected category
            foreach (Item item in _context.Items.Where(item => item.CategoryId == id))
            {
                _context.Items.Remove(item);
            }

            var categoryModel = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(categoryModel);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryModelExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

TecReview/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TecReview.Models;

namespace TecReview.Controllers
{
    public class ItemsController : Controller
    {
        private readonly TecReviewContext _context;
        private readonly IHostingEnvironment _env;

        private readonly string _itemsTransitionDataPath;

        public ItemsController(TecReviewContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;

            // If working in Visual Studio, make sure the 'Copy to Output Directory'
            // property of the file is set to 'Copy always'
            _itemsTransitionDataPath = System.IO.Path.Combine(_env.WebRootPath, "ml", "items-transition-data.txt");
        }

        [Authorize]
        // GET: Items
        public async Task<IActionResult> Index()
        {
            return View(await _context.Items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.Include(a => a.Category).FirstOrDefaultAsync(m => m.ItemId == id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        public async Task<IActionResult> MoveRelated(int? prevId, int? newId)
        {
            if (prevId == null || newId == null)
            {
                return NotFound();
            }
            
            string line = ((float) prevId).ToString("0.0") + ',' + ((float) newId).ToString("0.0");
            System.IO.File.AppendAllText(_itemsTransitionDataPath, line + Environment.NewLine);

            return RedirectToAction(nameof(Details), new {id = newId });
        }

        public async Task<IActionResult> Comments(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comments = await _context.Comments.Where(c => c.ItemId == id.Value).ToListAsync();

            if (comments == null)
            {
                return NotFound();
            }

            return Json(comments);
        }

        public async Task<IActionResult> Search(int? category, string header, string summary, DateTime? date)
        {
            var result = _context.Items.AsQueryable();

            if (category != null)
                result = result.Where(x => x.CategoryId == category);
            if (!String.IsNullOrWhiteSpace(header))
                result = result.Where(x => x.Header.Contains(header));
            if (!String.IsNullOrWhiteSpace(summary))
                result = result.Where(x => x.Summary.Contains(summary));
            if (date.HasValue)
                result = result.Where(x => x.DateCreated.Value.Date == date.Value.Date);

            return Json(result);
        }

        public async Task<IActionResult> GetRelatedItems(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            const int NUM_OF_RELATED_ITEMS = 3;
            var relatedItems = new List<Item>();

            try
            {
                int mlRelatedItem = MachineLearning.GetRelatedItem(_itemsTransitionDataPath, id.Value);

                if (mlRelatedItem != id.Value)
                {
                    var item = await _context.Items.FirstAsync(c => c.ItemId == mlRelatedItem);

                    if (item != null)
                    {
                        relatedItems.Add(item);

                        // Try to find a related item to the related item
                        int mlRelatedToRelatedItem = MachineLearning.GetRelatedItem(_itemsTransitionDataPath, mlRelatedItem);

                        if (mlRelatedToRelatedItem != mlRelatedItem && mlRelatedToRelatedItem != id.Value)
                        {
                            item = await _context.Items.FirstAsync(c => c.ItemId == mlRelatedToRelatedItem);

                            if (item != null)
                            {
                                relatedItems.Add(item);
                            }
                        }
                    }
                }

            }
            catch (Exception)
            {
            }

            int itemsCount = _context.Items.Count();
            Random random = new Random();

            // Fill the rest of the related items with random items, in order to
            // have the option for diversity (and by that make better predictions in the future)
            while (relatedItems.Count() < NUM_OF_RELATED_ITEMS)
            {
                int randomItemId = random.Next(1, itemsCount);

                if (randomItemId != id.Value && !relatedItems.Exists(c => c.ItemId == randomItemId))
                {
                    var randomItem = await _context.Items.FirstAsync(c => c.ItemId == randomItemId);

                    if (randomItem != null)
                    {
                        relatedItems.Add(randomItem);
                    }
                }
            }

            return Json(relatedItems);
        }

        // GET: Items/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Header,Summary,Content,HomeImageUrl,CategoryId,Location,IsShowMap")] Item itemModel)
        {
            if (ModelState.IsValid)
            {
                itemModel.DateCreated = DateTime.Now;
                _context.Add(itemModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");

            return View(itemModel);
        }

        // GET: Items/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");

            return View(item);
        }

        // POST: Items/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,Header,Summary,Content,HomeImageUrl,CategoryId,Location,IsShowMap")] Item item)
        {
            if (id != item.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Items.Attach(item);
                    _context.Entry(item).Property(x => x.Content).IsModified = true;
                    _context.Entry(item).Property(x => x.Header).IsModified = true;
                    _context.Entry(item).Property(x => x.Summary).IsModified = true;
                    _context.Entry(item).Property(x => x.HomeImageUrl).IsModified = true;
                    _context.Entry(item).Property(x => x.CategoryId).IsModified = true;
                    _context.Entry(item).Property(x => x.Location).IsModified = true;
                    _context.Entry(item).Property(x => x.IsShowMap).IsModified = true;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");

            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Items.FindAsync(id);
            _context.Items.Remove(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.ItemId == id);
        }
    }
}

TecReview/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using TecReview.Models;

namespace TecReview.Controllers
{
    public class SearchController : Controller
    {
        private readonly TecReviewContext _context;

        public SearchController(TecReviewContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Categories = _context.Categories.ToList<Category>();
            return View();
        }
    }
}

TecReview/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TecReview.Models;

namespace TecReview.Controllers
{
    [Authorize]
    public class StatisticsController : Controller
    {
        private readonly TecReviewContext _context;

        public StatisticsController(TecReviewContext context)
        {
            _context = context;
        }

        // GET: Statistics
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Comments()
        {
            var monthlyComments = await _context.Comments.GroupBy(c => new { c.DatePosted.Year, c.DatePosted.Month }).ToListAsync();

            var statistics = monthlyComments.Select(monthGroup => new {
                month = monthGroup.First().DatePosted.Month.ToString() + '/' + monthGroup.First().DatePosted.Year.ToString(),
                comments = monthGroup.Count()
            }).ToList();

            return Json(statistics);
        }

        public async Task<IActionResult> Items()
        {
            var itemsPerCategory = await _context.Items.Join(_context.Categories,
                category => category.CategoryId,
                item => item.CategoryId,
                (item, category) => new Item()
                {
                    ItemId = item.ItemId,
                    CategoryId = category.CategoryId,
                    Category = category
                }).GroupBy(x => x.CategoryId).ToListAsync();

            var statistics = itemsPerCategory.Select(categoryItems => new
            {
                label = categoryItems.First().Category.Name,
                color = categoryItems.First().Category.HexColor,
                value = categoryItems.Count()
            }).ToList();

            return Json(statistics);
        }

        public async Task<IActionResult> Locations()
        {
            var locations = await _context.Items.Select(item => item.Location).ToListAsync();

            return Json(locations);
        }
    }
}

TecReview/Views/Shared/_CategoryBadge.cshtml
@model TecReview.Models.Category

<a asp-controller="Categories" asp-action="Details" asp-route-id="@Model.CategoryId">
    <span class="badge badge-secondary" style="background-color: @Model.HexColor">@Html.DisplayFor(model => model.Name)</span>
</a>

TecReview/Views/Shared/_Comments.cshtml
@using Microsoft.AspNetCore.Identity
@using TecReview.Models

@model TecReview.Models.Item

@inject SignInManager<ApplicationUser> SignInManager


<script src="~/js/api.js" type="text/javascript"></script>

<!-------------------------------TEMPLATES--------------------------------->

<script id="commentTemplate" type="text/x-jQuery-tmpl">
    <div class="media mb-1 border-bottom">
        <div class="media-left mr-2">
            <h2>${sequence}.</h2>
        </div>
        <div class="media-body">
            <small>${author}</small>
            <p>${content}</p>
        </div>
        @if (SignInManager.IsSignedIn(User))
        {
            <button class="btn btn-danger btn-sm" onclick="delete_comment(${commentId}, @Model.ItemId)">Delete Comment</button>
        }

    </div>
</script>

<!-------------------------------POST COMMENT--------------------------------->

<div class="col-12">
    <h3>Comments</h3>
    <div class="border-bottom mb-2">
        <form id="newCommentForm">
            <div class="form-group form-group-sm">
                <input type="text" name="Author" class="form-control" placeholder="Who are you?" />
            </div>
            <div class="form-group form-group-sm">
                <textarea name="Content" class="form-control" rows="2" placeholder="And what do you think about this?"></textarea>
            </div>
            <div class="form-group form-group-sm">
                <input type="hidden" name="ItemId" class="form-control" value="@Model.ItemId" />
            </div>
            <div class="form-group form-group-sm">
                <button type="button" class="btn btn-success btn-sm mr-2" onclick="post_comment(@Model.ItemId)">Post Comment</button>
            </div>
        </form>
    </div>
    <div class="col-md-12">
        <div class="list-group" id="commentsList">
        </div>
    </div>
    <div id="result">

    </div>
</div>


<!-------------------------------DIALOGS--------------------------------->

<div class="modal fade" id="errorCommentModal" tabindex="-1" role="dialog" aria-labelledby="errorCommentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger" id="errorCommentModalLabel">Error</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">X</span>
                </button>
            </div>
            <div class="modal-body">
                Please fill both content and author
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

TecReview/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TecReview.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<header class="blog-header border shadow-sm">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                Home
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-auto">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item active">
                            <a asp-controller="Categories" asp-action="Index" class="nav-link">Categories</a>
                        </li>

                        <li class="nav-item active">
                            <a asp-controller="Items" asp-action="Index" class="nav-link">Items</a>
                        </li>

                        <li class="nav-item active">
                            <a asp-controller="Statistics" asp-action="Index" class="nav-link">Statistics</a>
                        </li>
                    }
                </ul>

                <ul class="navbar-nav">
                    <li class="nav-item ml-3">
                        <a class="text-muted" href="@Url.Action("Index", "Search")" style="vertical-align: super;">
                            <svg xmlns="http://www.w3.org/2000/svg" style="vertical-align: sub;" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
                                <circle cx="10.5" cy="10.5" r="7.5"></circle>
                                <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                            </svg>
                        </a>
                    </li>

                    <li class="nav-item">
                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <a href="https://twitter.com/TecReview?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-dnt="true" data-show-count="false">Follow Us</a>
                            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                        }
                    </li>

                    <li class="nav-item">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" class="form-inline my-2 my-lg-0">
                                <button type="submit" class="btn btn-secondary">Log out</button>
                            </form>
                        }
                        else
                        {
                            <a class="btn btn-secondary" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                        }
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

TecReview/Views/Shared/_ItemVertical.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@model TecReview.Models.Item

<div class="card" style="width: 18rem; background-color: #f2eeee">
    <a asp-controller="Items" asp-action="Details" asp-route-id="@Model.ItemId">
        <img data-toggle="tooltip"
             data-html="true"
             data-placement="bottom"
             title="@Html.DisplayFor(model => model.Summary)"
             class="card-img-top"
             data-src="holder.js/100px180/"
             alt="100%x180"
             style="height: 180px; width: 100%; display: block;"
             src="@Html.DisplayFor(model => model.HomeImageUrl)"
             data-holder-rendered="true">
    </a>
    <div class="card-body">
        <h5 class="card-title">@Html.DisplayFor(model => model.Header)</h5>
        <a class="btn btn-sm btn-outline-secondary" asp-controller="Items" asp-action="Details" asp-route-id="@Model.ItemId">Read more...</a>
    </div>
</div>

TecReview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TecReview</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/simplemde/dist/simplemde.min.css" />
        <link rel="stylesheet" href="~/fonts/Alef/Alef.css">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/items.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/items.min.css"/>
    </environment>
</head>
<body>
    @Html.Partial("_HeaderPartial")
    <div class="container">
        <div class="container body-content">
            @RenderBody()
            <hr />
            <aside>
                <footer>
                    <p class="footer-style">&copy; 2019 - TecReview</p>
                </footer>
            </aside>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-tmpl/jquery.tmpl.js"></script>
        <script src="~/lib/popper/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/showdown/dist/showdown.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/markdown.js"></script>
        <script src="~/lib/simplemde/dist/simplemde.min.js"></script>
        <script src="~/lib/fitty-gh-pages/dist/fitty.min.js"></script>
        <script src="~/js/api.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>